3 qz xing building instruction and version information
EDDragonWolf/QZXingBinaries pull request #3
Opened 2018-05-21 17:25 UTC by grafit7

2018-05-21 17:27 UTC, EDDragonWolf requested changes

2018-05-21 17:27 UTC, EDDragonWolf commented on README.md
> +`QT += multimedia
use ```<>```

2018-05-21 17:51 UTC, grafit7 commented on README.md
> +`QT += multimedia
Done

2018-05-22 09:00 UTC, EDDragonWolf approved these changes

2018-05-22 09:00 UTC, EDDragonWolf commented on README.md
> +# Additional import path used to resolve QML modules in Qt Creator's code model
Remove extra text

2018-05-22 09:00 UTC, EDDragonWolf commented on README.md
> +```
Add statement for cloning repo

2018-05-22 09:00 UTC, EDDragonWolf commented on README.md
> +### For windows you'll get:
Use bold, not header

2018-05-22 09:00 UTC, merged